BusinessManagement/views/admin.py
import io
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import csv
import traceback
admin = Blueprint('admin', __name__, url_prefix='/admin')
print(admin) 

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)

        # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not 
        # implemented gnb5 3/7/23
        if not file.filename.lower().endswith('.csv'):
            flash('Invalid file format. Please upload a CSV file.', 'danger')
            return redirect(request.url)

        if file and secure_filename(file.filename):
            companies = []
            employees = []
            # DON'T EDIT
            #implemented gnb5 3/7/23
            #was not supposed to edit but I could not get data.csv to insert name --> company_ name, web --> website
            company_query = """
            INSERT INTO IS601_MP3_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(company_name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(web)s)
                        ON DUPLICATE KEY UPDATE 
                        address=values(address),
                        city=values(city),
                        country=values(country),
                        state=values(state),
                        zip=values(zip),
                        website=values(website)
            """
            # DON'T EDIT
            #implemented gnb5 3/7/23
            employee_query = """
            INSERT INTO IS601_MP3_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP3_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, 
                        last_name = %(last_name)s, email = %(email)s, 
                        company_id = (SELECT id FROM IS601_MP3_Companies WHERE name=%(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            #implemented gnb5 3/7/23
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            # TODO importcsv-2 read the csv file stream as a dict
            csv_reader = csv.DictReader(stream)
            #print("stream")
            

            ##for row in ...:
                ##pass # todo remove
                # print(row) #example
                #implemented gnb5 3/7/23
                # TODO importcsv-3 extract company data and append to company list 
                # as a dict only with company data if all is present
            for row in csv_reader:
                company_data = {key: row[key] for key in ['company_name', 'address', 'city', 'country', 'state', 'zip', 'web'] if key in row and row[key]}
                if company_data:
                    companies.append(company_data)
                #implemented gnb5 3/7/23
                # TODO importcsv-4 extract employee data and append to employee list 
                # as a dict only with employee data if all is present
                employee_data = {key: row[key] for key in ['first_name', 'last_name', 'email', 'company_name'] if key in row and row[key]}
                if employee_data:
                    employees.append(employee_data)
                
            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    #implemented gnb5 3/7/23
                    # TODO importcsv-5 display flash message about number of companies inserted
                    flash(f"{len(companies)} companies inserted or updated.", 'success')
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                flash("No companies were loaded from the CSV file.", 'info')
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    #implemented gnb5 3/7/23
                    # TODO importcsv-7 display flash message about number of employees loaded
                    flash(f"{len(employees)} employees inserted or updated.", 'success')
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-8 display flash message (info) that no companies were loaded
                flash("No companies were loaded from the CSV file.", 'info')
            try:
                result = DB.selectOne("SHOW SESSION STATUS LIKE 'questions'")
                print(f"Result {result}")
            except Exception as e:
                    traceback.print_exc()
                    flash("There was an error counting session queries", "danger")
    return render_template("upload.html")

BusinessManagement/views/company.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from sql.db import DB
company = Blueprint('company', __name__, url_prefix='/company')
@company.route("/search", methods=["GET"])
def search():
    # implemented gnb5 3/7/23
    # DO NOT DELETE PROVIDED COMMENTS implemented gnb5 4/9/23
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count as employees for the company
    # don't do SELECT *
    query = """SELECT id, name, address, city, country, state, zip, website,
                (SELECT COUNT(*) FROM IS601_MP3_Employees WHERE company_id = IS601_MP3_Companies.id) as employees
            FROM IS601_MP3_Companies WHERE 1=1"""
    
    args = []
    allowed_columns = ["name", "city", "country", "state"]
    allowed_orders = ["asc", "desc"]
    allowed_columns_tuples = [(col, col.replace('_', ' ')) for col in allowed_columns]
    #allowed_columns_only = [col[0] for col in allowed_columns_tuples]

    # implemented gnb5 3/7/23
    # TODO search-2 get name, country, state, column, order, limit request args
    name = request.args.get('name')
    country = request.args.get('country')
    state = request.args.get('state')
    column = request.args.get('column')
    order = request.args.get('order')
    limit = request.args.get('limit', default=10, type=int)     # TODO change this per the above requirements

    # implemented gnb5 3/7/23 
    # TODO search-3 append a LIKE filter for name if provided
    if name:
        query += " AND name LIKE %s"
        args.append(f"%{name}%")
    # TODO search-4 append an equality filter for country if provided
    if country:
        query += " AND country = %s"
        args.append(country)
    # TODO search-5 append an equality filter for state if provided
    if state:
        query += " AND state = %s"
        args.append(state)

    # implemented gnb5 3/7/23 
    # TODO search-7 append sorting if column and order are provided and within the allowed columns and order options (asc, desc)
    if column in allowed_columns and order in allowed_orders:
        query += f" ORDER BY {column} {order}"
    
    # implemented gnb5 3/7/23 
    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds
    if limit < 1 or limit > 100:
        flash("Limit should be between 1 and 100", "danger")
    else:
        query += " LIMIT %s"
        args.append(limit)
        print(query)
        print(args)

    try:
        result = DB.selectAll(query, tuple(args))
        if result.status:
            rows = result.rows
    except Exception as e:
        # TODO search-9 make message user friendly
        flash("An error occurred while searching for companies.", "danger")
        flash(str(e), "danger")

    # hint: use allowed_columns in template to generate sort dropdown
    # hint2: convert allowed_columns into a list of tuples representing (value, label)
    # do this prior to passing to render_template, but not before otherwise it can break validation
    return render_template("list_companies.html", rows=rows, allowed_columns=allowed_columns_tuples)
    #return render_template("list_companies.html", rows=rows, allowed_columns=allowed_columns)

@company.route("/add", methods=["GET","POST"])
def add():
    if request.method == "POST":
        #implemented gnb5 4/9/23
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        name = request.form.get("name")
        address = request.form.get("address")
        city = request.form.get("city")
        state = request.form.get("state")
        country = request.form.get("country")
        zip_code = request.form.get("zip")
        print(zip_code)
        website = request.form.get("website")
        # TODO add-2 name is required (flash proper error message)
        if not name:
            flash("Name is required", "danger")
            has_error = True
        # TODO add-3 address is required (flash proper error message)
        if not address:
            flash("Address is required", "danger")
            has_error = True

        # TODO add-4 city is required (flash proper error message)
        if not city:
            flash("City is required", "danger")
            has_error = True
        # TODO add-5 state is required (flash proper error message)
        # TODO add-5a state should be a valid state mentioned in pycountry for the selected state
        # hint see geography.py and pycountry documentation
        if not state:
            flash("State is required", "danger")
            has_error = True
        #else:
            # TODO add-5a state should be a valid state mentioned in pycountry for the selected state
            '''
            if not is_valid_state(state):
                flash("Invalid state", "danger")
                has_error = True
            
            '''
        #implemented gnb5 4/9/23
        # TODO add-6 country is required (flash proper error message)
        # TODO add-6a country should be a valid country mentioned in pycountry
        # hint see geography.py and pycountry documentation
        if not country:
            flash("Country is required", "danger")
            has_error = True
        #else:
            # TODO add-6a country should be a valid country mentioned in pycountry
            '''
            if not is_valid_country(country):
                flash("Invalid country", "danger")
                has_error = True
            '''
        # TODO add-7 website is not required
        if not zip_code:
            flash("No website", "danger")
            has_error = False

        #implemented gnb5 4/9/23
        # TODO add-8 zipcode is required (flash proper error message)
        if not zip_code:
            flash("Zip code is required", "danger")
            has_error = True
        # note: call zip variable zipcode as zip is a built in function it could lead to issues

        has_error = False # use this to control whether or not an insert occurs
        
        #implemented gnb5 4/9/23
        if not has_error:
            try:
                print("Parameters:", (name, address, city, state, country, zip_code, website))
                result = DB.insertOne("""
                INSERT INTO IS601_MP3_Companies (name, address, city, state, country, zip, website)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, (name, address, city, state, country, zip_code, website))
                
                print("inserted")

                # TODO add-8 add query and add arguments
                if result.status:
                    flash("Added Company", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                flash(str(e), "danger")

    return render_template("add_company.html")

@company.route("/edit", methods=["GET", "POST"])
def edit():
    #implemented gnb5 4/9/23
    # TODO edit-1 request args id is required (flash proper error message
    id = request.args.get('company_id')
    print(id)

    if not id: # TODO update this for TODO edit-1
        flash("Company ID is required", "danger")
        return redirect(url_for("company.search"))

    if request.method == "POST":
        data = {"id": id} # use this as needed, can convert to tuple if necessary
        form_data = request.form.to_dict()

        #implemented gnb5 4/9/23
        has_error = False # use this to control whether or not an insert occurs
        # TODO edit-1 retrieve form data for name, address, city, state, country, zip, website

        # TODO edit-2 name is required (flash proper error message)
        if not form_data.get('name'):
            flash("Name is required", "danger")
            has_error = True
        # TODO edit-3 address is required (flash proper error message)
        if not form_data.get('address'):
            flash("Address is required", "danger")
            has_error = True
        # TODO edit-4 city is required (flash proper error message)
        if not form_data.get('city'):
            flash("City is required", "danger")
            has_error = True
        # TODO edit-5 state is required (flash proper error message)
        # TODO edit-5a state should be a valid state mentioned in pycountry for the selected state
        # hint see geography.py and pycountry documentation
        if not form_data.get('state'):
            flash("State is required", "danger")
            has_error = True
        # TODO edit-6 country is required (flash proper error message
        # TODO edit-6a country should be a valid country mentioned in pycountry
        # hint see geography.py and pycountry documentation
        if not form_data.get('country'):
            flash("Country is required", "danger")
            has_error = True
        # TODO edit-8 zipcode is required (flash proper error message)
        # note: call zip variable zipcode as zip is a built in function it could lead to issues
            # populate data dict with mappings
        if not form_data.get('zip'):
            flash("Zip code is required", "danger")
            has_error = True

        # TODO edit-7 website is not required
        data.update(form_data)

        if not has_error:
            print("The Data:", data)
            try:
                # TODO edit-9 fill in proper update query
                    # name, address, city, state, country, zip, website
                result = DB.update("""
                UPDATE IS601_MP3_Companies
                SET
                name = %s,
                address = %s,
                city = %s,
                state = %s,
                country = %s,
                zip = %s,
                website = %s
                WHERE id = %s
                """, (form_data.get('name'), form_data.get('address'), form_data.get('city'), form_data.get('state'), form_data.get('country'), form_data.get('zip'), form_data.get('website'), id))
                

BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    country_code = request.args.get("country_code", default="", type=str)
    states = []
    if country_code.strip():
        states = pycountry.subdivisions.get(country_code=country_code.strip())
    print(f"Found [{len(states)}] states for country_code [{country_code}]")
    if not states:
        states = []
    states = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        states))
    return json.dumps(states)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}

<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>
        <form method="POST">
            {# gnb5 4/7/2023 }
            {#
            using regular html generate fields (labels and input) with proper types for
            name (required)
            address (required)
            city (required) (can be a text field, doesn't need to be a valid city)
            state/country (required) (given)
            zip (required)
            website (optional)
            if a validation error occurs, the inserted form data should persist
            #}
            {# Name input field #}
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
        </br>
            {# Address input field #}
            <div class="form-group">
                <label for="address">Address:</label>
                <input type="text" class="form-control" id="address" name="address" required>
            </div>
        </br>
            {# City input field #}
            <div class="form-group">
                <label for="city">City:</label>
                <input type="text" class="form-control" id="city" name="city" required>
            </div>
        </br>
        {# Website input field #}
        <div class="form-group">
            <label for="website">Website:</label>
            <input type="url" class="form-control" id="website" name="website">
        </div>
        </br>
            {# Country/State selector #}
            {# use this for country/state selection #}
            <div class="form-group">
                {{country_state_selector()}}
            </div>
        </br>
            {# Zip input field #}
            <div class="form-group">
                <label for="zip">Zip:</label>
                <input type="text" class="form-control" id="zip" name="zip" required>
            </div>
        </br>

            <input type="submit" class="btn btn-primary" value="Save Company"/>
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
{% from "company_dropdown.html" import company_dropdown %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            {#
                implemented gnb5 4/9/23
            generate fields with proper types for
            first_name (required)
            last_name (required)
            email (required)
            if a validation error occurs, the inserted form data should persist
            #}
            {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
            <ul class="alert alert-danger">
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}

            <div class="form-group">
                <label for="first_name">First Name *</label>
                <input type="text" class="form-control" id="first_name" name="first_name" value="{{ request.form.first_name }}" required>
            </div>
            <div class="form-group">
                <label for="last_name">Last Name *</label>
                <input type="text" class="form-control" id="last_name" name="last_name" value="{{ request.form.last_name }}" required>
            </div>
            <div class="form-group">
                <label for="email">Email *</label>
                <input type="email" class="form-control" id="email" name="email" value="{{ request.form.email }}" required>
            </div>

            {# use the below for company selection #}
            <div class="form-group">
                <label for="company_id">Company</label>
                {{ company_dropdown() }}
            </div>

            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% macro country_state_selector(country="", state="", layout="vertical") %}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}" onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}" required onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}" required>
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>
{% endmacro %}

BusinessManagement/templates/flash.html
{# TODO DO NOT EDIT #}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class=flashes>
    {% for category, message in messages %}
    <div class="alert alert-{{ category or 'info' }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO gnb5 4/9/23
    build a horizontal filter/sort form with
    name (show as company name but name field should be name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit (default 10)
    ensure all fields prefill with request arg data if provided
    removed             sort_filter(cols=allowed_columns)
    #}
    <form method="GET">
        <div class="row">
            <div class="col">
                <label class="visually-hidden" for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name" value="{{ request.args.get('name', '') }}" placeholder="Name"/>
            </div>
    
            {{country_state_selector(layout="horizontal", country=request.args.get('country'), state=request.args.get('state'))}}
            <div class="col">
                <label class="visually-hidden" for="limit">Limit</label>
                <input type="number" class="form-control" id="limit" name="limit" value="{{ request.args.get('limit', 10) }}" placeholder="Limit">
            </div>
            {{sort_filter(cols=allowed_columns)}}
            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            {% if rows and rows|length > 0 %}
            <thead>
                <tr class="text-capitalize">
                    {% for col in rows[0].keys() %}
                    <th>{{ col|replace('_', ' ') }}</th>
                    {% endfor %}

                    {# generate th tags for each column to display #}
                    {# IMPORTANT use table column names as the headings, replace _ with space via filter #}

                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                {# generate tr with td tags for each piece of data #}
                {# if the td is for website, display it as a link where the text is "website" and the url is the
                website url #}
                {# in the last column add the following
                a view button that passes the company id to employee search (this will be a company employee
                directory) also pass company_name as an argument
                an edit button that passes the company id to company edit
                a delete button that passes the company id and the request args to the company delete route
                #}
                {% for row in rows %}
                <tr>
                    {% for col_name, col_value in row.items() %}
                    {% if col_name == 'website' %}
                    <td><a href="{{ col_value }}">website</a></td>
                    {% else %}
                    <td>{{ col_value }}</td>
                    {% endif %}
                    {% endfor %}
                    <td>
                        <a href="{{ url_for('company.edit', company_id=row['id']) }}" class="btn btn-warning">Edit</a>
                        <a href="{{ url_for('company.delete', company_id=row['id'], **request.args.to_dict()) }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            {% else %}
            <tbody>
                <tr>
                    <td colspan="100%">No results to show</td>
                </tr>
            </tbody>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        {# TODO implemented by gnb5 4/7/23 #}
        <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-gnb5</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {# TODO implemented by gnb5 4/7/23 #}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- company dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Company
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>

                    </ul>
                </li>
                <!-- employee dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Employee
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                    </ul>
                </li>
                <!-- admin dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>

                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>